language: elixir

otp_release:
  - 20.0

elixir:
  - 1.5.3

sudo: false

script:
  - rm -rf _build
  - mix test --trace

services:
  - postgresql

addons:
  postgresql: "9.4"

before_install:
  - cp config/dev.secret.exs.example config/dev.secret.exs

before_script:
  - cp config/test.secret.exs.example config/test.secret.exs
  - psql -c 'create database ex_money_test;' -U postgres
